# Generated by Django 4.0.1 on 2022-01-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Swiper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='maximal 128 Zeichen', max_length=128, verbose_name='überschrift')),
                ('image', models.ImageField(help_text='maximale Bildauflösung 1920x717', upload_to='images/swiper', verbose_name='bild')),
                ('text', models.TextField(help_text='maximale Länge 512 Zeichen', max_length=256, verbose_name='text eingeben')),
            ],
            options={
                'verbose_name': 'swiper',
            },
        ),
    ]
