# Generated by Django 4.2 on 2023-05-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Treatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "category",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Kosmetische Behandlungen"),
                            (2, "Nageldesign"),
                            (3, "Permanent Make Up"),
                            (4, "Körperenthaarung"),
                            (5, "Fußpflege"),
                        ],
                        default=1,
                        verbose_name="Leistungen",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Beschreibung",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Preise",
                    ),
                ),
            ],
            options={
                "verbose_name": "Behandlung",
                "verbose_name_plural": "Behandlungen",
                "ordering": ["name"],
            },
        ),
    ]
