# Generated by Django 4.0.1 on 2022-01-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='maximal 128 Zeichen', max_length=128, null=True, verbose_name='überschrift')),
                ('image', models.ImageField(help_text='maximale Bildauflösung 1920x717', upload_to='images/swiper', verbose_name='bild')),
            ],
        ),
    ]
