# Generated by Django 4.2 on 2023-05-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treatment",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Beschreibung"),
        ),
    ]
