# Generated by Django 4.0.1 on 2022-01-10 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_carousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='name')),
                ('last_name', models.CharField(max_length=120, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(help_text='max. 500 Zeichen', verbose_name='nachricht')),
            ],
            options={
                'verbose_name': 'kontaktanfrage',
                'verbose_name_plural': 'kontaktanfragen',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(help_text='maximale Bildauflösung 370x370', upload_to='images/swiper', verbose_name='bild'),
        ),
    ]
