# Generated by Django 4.2 on 2023-05-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_treatment_options_monthlyoffer"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlyoffer",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, null=True, verbose_name="Preise"
            ),
        ),
    ]
