# Generated by Django 4.2 on 2023-05-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_category_gallery_alter_treatment_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=64, verbose_name="Vorname")),
                ("last_name", models.CharField(max_length=64, verbose_name="Nachname")),
                ("text", models.TextField(verbose_name="Bewertung")),
            ],
            options={
                "verbose_name": "Bewertung",
                "verbose_name_plural": "Bewertungen",
                "ordering": ("last_name",),
            },
        ),
    ]
