# Generated by Django 4.2 on 2023-05-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_testimonial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="gallery", verbose_name="Galeriebild"),
                ),
                (
                    "description",
                    models.CharField(max_length=28, verbose_name="Kurzbeschreibung"),
                ),
            ],
            options={
                "verbose_name": "Bild",
                "verbose_name_plural": "Bilder",
            },
        ),
    ]
